### ISSUE TITLE
Migrate to new Boto3 AWS Python SDK

### ISSUE THREAD

**Issue by hjacobs** [zalando/stups-etcd-cluster#3]
The old boto library is deprecated.
https://boto3.readthedocs.org/en/latest/guide/migration.html

**Comment by a1exsh** [comment]
Well, it is not literally deprecated, but I see the point.

**Comment by hjacobs** [comment]
We had sporadic problems with the HMAC signature in ZMON using the old "boto" library (it did not appear again after upgrading to boto3).

**Comment by CyberDem0n** [comment]
Migrated
