### ISSUE TITLE
HouseKeeper: Type str doesn't support the buffer API

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/stups-etcd-cluster#9]
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]: ERROR  2016-01-11 05:26:12,831 - Exception in HouseKeeper main loop
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]: Traceback (most recent call last):
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]:  File "/bin/etcd.py", line 433, in run
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]:    if (update_required or self.members_changed() or self.cluster_unhealthy()) and self.acquire_lock():
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]:  File "/bin/etcd.py", line 386, in cluster_unhealthy
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]:    ret = any([True for line in process.stdout if 'is unhealthy' in line])
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]:  File "/bin/etcd.py", line 386, in <listcomp>
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]:    ret = any([True for line in process.stdout if 'is unhealthy' in line])
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]: TypeError: Type str doesn't support the buffer API
06:26:12.000  Jan 11 05:26:12 ip-172-31-166-204 docker/a9251b73b92c[785]: DEBUG  2016-01-11 05:26:12,833 - Sleeping 30 seconds...

**Comment by CyberDem0n** [comment]
Which docker image was used for that stack?
This error was fixed long time ago: https://github.com/zalando/stups-etcd-cluster/blob/master/etcd.py#L421

**Comment by feikesteenbergen** [comment]
The report originates from a very old etcd cluster; it was mistakenly assumed it was a very recent one.
